services:
  swatreview:
    image: registry.sccs.swarthmore.edu/cs77-s25/swatreview/swatreview:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
    #env_file:
    #  - .env
      DOMAIN: https://swatreview.sccs.swarthmore.edu/
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik"
        - "traefik.http.routers.swatreview.entrypoints=https"
        - "traefik.http.routers.swatreview.rule=Host(`swatreview.sccs.swarthmore.edu`)"
        - "traefik.http.routers.swatreview.tls=true"
        - "traefik.http.routers.swatreview.tls.certresolver=letsEncrypt"
        - "traefik.http.services.swatreview.loadbalancer.server.port=5000"
    networks:
      - internal
      - traefik

networks:
  internal:

  traefik:
    external: true
