"""add daily_rating to Dish

Revision ID: 054fa572bb1e
Revises: 
Create Date: 2025-04-19 20:58:31.714445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '054fa572bb1e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dish', schema=None) as batch_op:
        batch_op.add_column(sa.Column('daily_rating', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dish', schema=None) as batch_op:
        batch_op.drop_column('daily_rating')

    # ### end Alembic commands ###
